# Generated by Django 2.1.1 on 2018-09-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180814_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('weekday', models.SmallIntegerField()),
                ('course', models.CharField(max_length=60, null=True)),
                ('room', models.CharField(max_length=60, null=True)),
                ('teacher', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('parent', models.CharField(max_length=60, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('overtime', models.SmallIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pcr_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.SmallIntegerField(default=-6),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.DayofWeek'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['pcr_id'], name='students_st_pcr_id_2358a0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'last_name'], name='students_st_grade_6cdd63_idx'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='studentsession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='students.Student'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='students.Student'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['student', 'weekday', 'course', 'room', 'start', 'end'], name='students_sc_student_998edb_idx'),
        ),
    ]
