# Generated by Django 2.1.1 on 2018-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180926_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='split_billing',
            field=models.BooleanField(default=False),
        ),
    ]
