# Generated by Django 2.1.1 on 2018-10-05 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_split_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parent', models.CharField(max_length=60, null=True)),
                ('duration', models.SmallIntegerField(default=0)),
                ('overtime', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_pays',
            field=models.SmallIntegerField(default=100, help_text='-1 for split based on parent pick-up, 0 for no charge'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='studentsessionsgroup',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='session_group', to='students.StudentSession'),
        ),
        migrations.AddField(
            model_name='studentsessionsgroup',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_groups', to='students.Student'),
        ),
    ]
