# Generated by Django 2.1.1 on 2018-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181004_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'last_name'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='studentsession',
            options={'ordering': ['-end'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='studentsessionsgroup',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='studentsession',
            name='waive_fees',
            field=models.BooleanField(default=False),
        ),
    ]
