# Generated by Django 2.1.1 on 2018-10-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20181005_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsession',
            options={'ordering': ['start'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='studentsessionsgroup',
            options={'ordering': ['-date', 'student__grade', 'student__last_name']},
        ),
    ]
