# Generated by Django 2.1.1 on 2018-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20181031_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='source',
            field=models.CharField(default='manual', max_length=60),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['student', 'weekday'], name='students_sc_student_fe7b04_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['student', 'weekday', 'start'], name='students_sc_student_cdb659_idx'),
        ),
    ]
