# Generated by Django 2.1.1 on 2020-05-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200521_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='students.Staff'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='students.Student'),
        ),
    ]
