# Generated by Django 2.1.1 on 2020-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200521_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scanner',
        ),
        migrations.AddField(
            model_name='scan',
            name='scanners',
            field=models.ManyToManyField(null=True, related_name='scans_recorded', to='students.Staff'),
        ),
    ]
